on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'gcp/cloud-functions/TEMPLATE--etl-live-1-extract/**'

jobs:
  deploy-gcp-cloud-function:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_CREDENTIALS_JSON }}'

      - name: Deploy Cloud Function (Gen 2)
          run:|
            gcloud functions deploy TEMPLATE--etl-live-1-extract \
            --gen2 \
            --region us-east1 \
            --runtime nodejs18 \
            --source gcp/cloud-functions/TEMPLATE--etl-live-1-extract \
            --entry-point extract \
            --memory 8192MB \
            --timeout 540s \
            --trigger-topic test
            --service-account test-648@bits-sandbox-450720.iam.gserviceaccount.com # Ensure this SA has the correct permissions.'
